### ISSUE TITLE
Upcoming events don't appear in the home page

### ISSUE THREAD

**Issue by kikito** [phoet/on_ruby#161]
It seems to me that the home page (of every label) always says "there are no planned upcoming events" even if there are upcoming events planned, right?

I think I can send a PR to fix that (I might need help with the German).

**Comment by phoet** [comment]
It shows the next upcoming event within two weeks. So maybe you need to
tweak the duration to suit your needs
Am 20.01.2015 22:49 schrieb "Enrique García" <notifications@github.com>:

**Comment by phoet** [comment]
it's actually 8 weeks https://github.com/phoet/on_ruby/blob/ca15c0572fa762422b053a60e3d179e120530d76/app/models/event.rb#L25 but i think this has to do with cache expiry. fixing this right now.

**Comment by kikito** [comment]
:clap: :clap:
