### ISSUE TITLE
Material Preview (& delayed jobs question)

### ISSUE THREAD

**Issue by kikito** [phoet/on_ruby#164]
One of the things I would like to do in Madrid.rb is to show the materials (mostly the videos) right there in the event page.

I have been studying options and the one that I like the most is using [link_thumbnailer](https://github.com/gottfrois/link_thumbnailer).

link_thumbnailer works similarly to the "facebook preview". When you give it a url, it actually downloads the html of that url, and extracts info from several `meta` fields. It also finds "relevant images" by crawling the site.

... Unfortunately, this takes time. Calling `link_thumbnailer` directly from the view kills the connection almost 80% of the time on my machine. So this needs needs to be done in a background process. Then we can store the thumbnail information in the database, after creating/updating a Material, where it can be accessed at acceptable speed from the view.

Which brings me to my first question: Is it ok to add a delayed job system to on_ruby? And if so, which one is appropriate? For minimal extra dependencies I would go with [delayed_job_active_record](https://devcenter.heroku.com/articles/delayed-job), but we could also go with resque ([redistogo](https://addons.heroku.com/redistogo) seems to be free for nano instances).

EDIT: note that if this is not possible, I can still try to do something like "work after rendering", as explained in [this SO question](http://stackoverflow.com/questions/8167381/how-to-perform-some-task-after-render-in-rails-3-1). I think it would be less clean, but doable. So don't feel super pressured to say yes to workers.

**Comment by phoet** [comment]
I think workers is fine. I'll go and give suckerpunch a shot as it's basically dependency free and perfect for this kind of one off jobs.

In addition to that I'll add a cron that can process missing previews and migrate the old data.

So for the first version just go ahead and implement it inline. We can see how this behaves on heroku.

**Comment by kikito** [comment]
> So for the first version just go ahead and implement it inline

Please clarify. By "inline" you mean using workers (which queue?) or using suckerpunch?

**Comment by phoet** [comment]
sorry, what i meant was to implement it without any job/worker first. moving it to something like suckerpunch afterwards should be fairly simple. is that ok for you, or do you want to go ahead and have it all in one go?

**Comment by kikito** [comment]
Ok, understood. I will see what I can do.

**Comment by phoet** [comment]
:+1: awesome!

**Comment by phoet** [comment]
closed via #166
