### ISSUE TITLE
The 'events' page is not linked from the index page sometimes

### ISSUE THREAD

**Issue by kikito** [phoet/on_ruby#167]
In particular, there is no link when there're no planned events. There should be a 'see past events' link somewhere.

**Comment by phoet** [comment]
i'm not quite sure what you mean here, can you take a screenshot? all the past events should be accessible from the hompage.

![madrid rb - grupo de usuarios de ruby de madrid 2015-02-08 13-41-05](https://cloud.githubusercontent.com/assets/48745/6096565/32116a4c-af98-11e4-99bc-51ad0057f44f.png)

**Comment by phoet** [comment]
hm, maybe this was a caching glitch. the fragments expire after 4 hours, so after that it might have fixed itself. i'm not super proud of the caching and invalidation logic right now, but it works most of the time.

**Comment by kikito** [comment]
Hm. Almost definitively a cache thing. Thanks, I will close this down
