### ISSUE TITLE
Please add madridrb.com CNAME options in production

### ISSUE THREAD

**Issue by kikito** [phoet/on_ruby#168]
Hi again!

We have (finally) purchased our domain name (madridrb.com). It is (kindof) pointing to madridrb.onruby.de in our end as the Readme says. Can you make the appropiate adjustments in heroku so that it says madridrb.com instead of madridrb.onruby.de?

Thanks!

**Comment by phoet** [comment]
Yes, I will take care of it today and let you know
Am 08.02.2015 01:30 schrieb "Enrique García" <notifications@github.com>:

**Comment by phoet** [comment]
i added the domain to heroku, what needs to be done now is that you CNAME the dns to point to `onruby.herokuapp.com` instead of performing a redirect. 

here is an example from rug-b.de:

```bash
± |master ✓| → dig www.rug-b.de

; <<>> DiG 9.8.3-P1 <<>> www.rug-b.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16644
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.rug-b.de.			IN	A

;; ANSWER SECTION:
www.rug-b.de.		86341	IN	CNAME	onruby.herokuapp.com.
onruby.herokuapp.com.	35	IN	A	54.247.182.234

;; Query time: 2 msec
;; SERVER: 10.0.1.1#53(10.0.1.1)
;; WHEN: Sun Feb  8 13:33:05 2015
;; MSG SIZE  rcvd: 80
```

**Comment by phoet** [comment]
i just purchased onruby.eu. all domains should be available through that TLD shortly. `madridrb.onruby.eu` will be the fallback for your usergroup

**Comment by kikito** [comment]
This is done - madridrb.com is up and running! 

Thanks for the help.

**Comment by phoet** [comment]
:tada: great! if you need anything else, let me know!
