### ISSUE TITLE
Problems when logging in to madridrb.com

### ISSUE THREAD

**Issue by kikito** [phoet/on_ruby#169]
Hi again,

Sorry to be such a pain. It seems that we've got a problem when logging in to madridrb.com:

* When clicking the "Github login" in the account menu, we get to [this link](https://github.com/login/oauth/authorize?client_id=&redirect_uri=http%3A%2F%2Fwww.madridrb.com%2Fauth%2Fgithub%2Fcallback&response_type=code&state=a1b3a0210dead105cf8274e0fbdfa0dc221c2b976f967213) which is a "page not found" on github. Do we need to change anything to make github work?
* When clicking on "Twitter login", it tells us to authorize hamburg-on-ruby (attaching screenshot). This will be confusing to people. Nevertheless, the login seems to work (clicking the button opens a session in madridrb.com)
![twitter authorize an application](https://cloud.githubusercontent.com/assets/63131/6125421/1f0b4b32-b116-11e4-8aee-a1c18f42051b.png)

Do I need to change anything to make github work? Is it possible to display madridrb.com instead of hamburg in the twitter login screen?

**Comment by phoet** [comment]
@kikito sorry, my fault! forgot to create a new application for github auth. unfortunately there is no way currently to support multiple redirect domains with their auth. i added a new one and you should be able to login using github.

for twitter i generalized the information so it should fit all the usergroups:

![screen shot 2015-02-10 at 18 29 56](https://cloud.githubusercontent.com/assets/48745/6132475/0c3fdea4-b153-11e4-9c95-085c3b6e0396.png)

**Comment by kikito** [comment]
Awesome, it works now! Closing this down
