### ISSUE TITLE
Make an "all events webcal" without needing to login/attend

### ISSUE THREAD

**Issue by kikito** [phoet/on_ruby#171]
The existing webcal (#99) does not show if you are not logged in. And (i think) it only shows the events you are attending.That does not cover the following use case: people who want to use their calendars to know when the next meeting is, and then decide whether they want to register or not (in fact, I got this exact thing requested on twitter).

I suggest putting a "Subscribe to all the Events of the group" link on the /events page. This should appear for everyone, not just logged in users, and should show all the events, independently of whether you are attending to them or not.

The Spanish translation is "Subscribirse a todos los Eventos del grupo", btw :)

**Comment by kikito** [comment]
Here's the tweet requesting the feature, btw: https://twitter.com/jcea/status/566213109799723009

**Comment by phoet** [comment]
this functionality is already there. `/events.ics` has all the usergroups events. unfortunately it's not linked anywhere... 

we have 3 types of calendar feeds:

* an event feed
* a user feed
* all events

maybe we can come up with an easier/better way to to this...

**Comment by kikito** [comment]
> maybe we can come up with an easier/better way to to this...

Well first of all, I think Events#show - should display links related to the single event, but not related to "other events" (besides a "see all events" link, which is missing IMHO). In other words, the "individual event ics link" belongs in Events#show, but the "all the events I am attending" should be in Events#index instead.

If you are ok with #173, I can extend it a little bit so that it also includes "all the events I am attending" only when logged in.

**Comment by phoet** [comment]
awesome, thx for the PR! please go ahead and add the personal calender as well.

**Comment by kikito** [comment]
Ok, I've moved the links, they are on the PR
