### ISSUE TITLE
"About me" field in user profiles

### ISSUE THREAD

**Issue by kikito** [phoet/on_ruby#172]
Some people are requesting an "about me" or "bio" field on their profile - probably markdown-enabled. This piece of text could be used to say a small thing about you - it can be what you like, where you work, etc.

I'm picturing this appearing in the topic/show page, if the person giving the topic has filled it up. Having some information about the speaker is a nice way for the to make other peripheral projects and interests visible, and will help others decide whether they want to attend the meeting.

**Comment by phoet** [comment]
there is a `user.description` field that's already populated with data from github or twitter. we could easily make that editable and show it somewhere.

**Comment by phoet** [comment]
made the field editable on the profile-edit-page. it's displayed as markdown on the public profile page. if you want to have it anywhere else please do a scribble or best a pr :smile_cat:
