### ISSUE TITLE
Madridrb.com stopped working

### ISSUE THREAD

**Issue by kikito** [phoet/on_ruby#204]
Hi there, Madridrb.com seems to have stopped working, but madridrb.onruby.eu still works. Is it possible that the onruby heroku app has changed Ip addresses? (I can't check, on mobile only atm)

If different Ip, is there a way to configure my dns so that they can cope with this kind of change in the future?

**Comment by bitboxer** [comment]
Looks like the domain does not resolve at all:

https://dnschecker.org/#A/Madridrb.com <https://dnschecker.org/#A/Madridrb.com>

So it is not an IP change. Can you check the nameserver configuration for the domain?

**Comment by kikito** [comment]
Not from where I am. Thanks for checking anyway, I will try to fix this
when I get to a proper computer.

**Comment by phoet** [comment]
looks like the DNS is still broken

**Comment by kikito** [comment]
Yes, unfortunately I don't have direct control over the dns configuration, and the person who has it is a bit unavailable at the moment. Depending on his responsiveness, I might have to change our domain to something else.
