### ISSUE TITLE
A new design for onruby.de/eu

### ISSUE THREAD

**Issue by joermungandr** [phoet/on_ruby#207]
Some comments from Nico:
– Marker per meetup if there will be (free/non-free; vegetatian/vegan) drinks/food
– Creating HTML slides that can be used to present at the user group (logo, list of talks (with speaker and their data available on the website), date of next meeting, Link to submit talk, …)
– Announcement emails which can be send to the UG’s mailing list with one click having all available information in

**Comment by joermungandr** [comment]
This is a big thing. We have to split it into several tickets, if we know what we want to do :-)

**Comment by phoet** [comment]
i think that no 2 & 3 should be their own tickets as they don't have much to do with a redesign. no 3 is also kinda implemented already: https://github.com/phoet/on_ruby/blob/master/app/mailers/usergroup_mailer.rb

**Comment by hagenburger** [comment]
I would move all points listed above into separate stories. They are completely independent of a new theme for the website.
