### ISSUE TITLE
Location might be off for huge buildings

### ISSUE THREAD

**Issue by PragTob** [phoet/on_ruby#211]
We have a little problem with the location for our [current meetup](http://www.rug-b.de/events/may-meetup-anniversary-2016)

The address is right, the building is big and so the position of the pin is way off. It goes to 38a, not 38. Incidentally, that is also a past venue (some cache or something maybe? Seems unlikely though)

In the picture below, the pin should be at Wooga not adjust :)

![selection_007](https://cloud.githubusercontent.com/assets/606517/15124849/3f0d7b24-162a-11e6-9938-eb56145f33ee.png)

Any idea how I could fix this (now through input - already tried updating it but didn't work). Don't have time right now but my idea to fix would be:

See if we can feed the company name to geocoder. At least in google maps looking for the address [yields the result as shown in the screenshot](https://www.google.com/maps/place/Saarbr%C3%BCcker+Str.+38,+10405+Berlin,+Germany/@52.5283101,13.4132107,17z/data=!3m1!4b1!4m5!3m4!1s0x47a84e1ceeeb81c9:0x1abbac851729ab4f!8m2!3d52.5283101!4d13.4154047), prepending it with "Wooga" leads to the [desired result](https://www.google.com/maps/place/Wooga/@52.5287037,13.4139955,17z/data=!3m1!4b1!4m5!3m4!1s0x47a84e05ac31e3a9:0x69f3e8333126bae7!8m2!3d52.5287037!4d13.4161895)

Not really a bug as technically it works, the above solution might help. Otherwise, it could be a solution to optionally manually enter lat/long

Thanks and still :heart:  on_ruby

**Comment by phoet** [comment]
it might be as simple as adding the name to [the full address](https://github.com/phoet/on_ruby/blob/master/app/models/location.rb#L8). i won't be able to look into this any time soon as i'm on parental leave for the next 2 month.

**Comment by phoet** [comment]
unfortunately, the geocoder has the same result when the name is added:

```
irb(main):032:0> Geocoder.coordinates("Saarbrücker Straße 38, 10405 Berlin")
=> [52.5283101, 13.4154047]
irb(main):033:0> Geocoder.coordinates("Wooga, Saarbrücker Straße 38, 10405 Berlin")
=> [52.5283101, 13.4154047]
```

**Comment by PragTob** [comment]
thanks for looking at it and sorry for me not looking at it.

Sad that it won't work :| Only solution that comes to my mind then is manually entering it which of course is also more work :|

**Comment by phoet** [comment]
putting the name second seems to work
```
irb(main):038:0> Geocoder.coordinates("Saarbrücker Straße 38, Wooga, 10405 Berlin")
=> [52.53419359999999, 13.4230065]
```

**Comment by phoet** [comment]
oh no, that's actually far off :D reverting it
