### ISSUE TITLE
http://meetu.ps/s/.0/wHmtR/d

### ISSUE THREAD

**Issue by Kristyp** [phoet/on_ruby#214]

**Comment by phoet** [comment]
This issue is missing a description.

**Comment by waterlink** [comment]
Seems to be a spam.. Meet-up under that link has 25 millions members..

**Comment by PragTob** [comment]
More likely a troll who wanted us to join meetup (link is an invitation to meetup itself) and all of the [public activity](https://github.com/Kristyp?tab=activity) is reporting issues here an forking something

**Comment by waterlink** [comment]
Yeah..
