### ISSUE TITLE
Ruby Berlin funds for working on this project?

### ISSUE THREAD

**Issue by ninabreznik** [phoet/on_ruby#218]
Hey, was having a debate with @PragTob and @argorak regarding possible funds for this app...

I just figured out that meetup.com was charging [us](http://www.meetup.com/codingamigos) 12$/year 3 years ago and now it somehow came to 30$ for half a year. So was asking on Twitter what were the alternatives and people from the scene mentioned this **on_ruby project** and that  _'Ruby Berlin has voted for investing money if someone who wants to do the work can be found.'_

So, we at [Coding Amigos](http://www.codingamigos.com) are working on [RefugeesWork](http://www.refugeeswork.com) and also teaching newcomers coding so was thinking, maybe this could be 'paid project' in _RailsGirlsSummerOfCode style_ where we could pay mentor and learner to teach and learn (mentors here are self employed hacktivists that also need to pay their bills) and make the project happen.

I do RoR, but also now learning and teaching JS (NPM style) so we could maybe use this app as an API and build a new frontend and make it web and mobile...

What are your thoughts?

**Comment by bitboxer** [comment]
We need to include the head of ruby berlin e.v. into this discussion: @bascht , please join :wink: .

**Comment by bascht** [comment]
@bitboxer Thanks for the ping. I'll find some time tonight to give a proper answer – but just to be sure that we're on the same page here: Is this about funds for on_ruby or about paying mentors for a SoC project?

**Comment by ninabreznik** [comment]
Hey, guys, thanks for the answer. I am an ex RGSoC student, but now I am mentoring refugees, teaching them JS. So that's the background :)

**Comment by phoet** [comment]
i'm still unsure what this is all about :)

- who is going to build something?
- what is going to be built?
- where do the funds come from?
- what problem is it going to solve?

**Comment by ninabreznik** [comment]
I was checking for alternative for Meetup.com and people told me about on_ruby and someone posted this: 'Ruby Berlin has voted for investing money if someone who wants to do the work can be found.'

So I thought, let's see what needs to be done and we at www.meetup.com/codingamigos could do that together with refugees that we teach coding...

**Comment by phoet** [comment]
i'd vote for the following things

1) do a redesign
2) rewrite the css part based on some standard like bootstrap or something similar

other than that i think that the tool kinda get's the job done. i'm unsure if there are features that are missing and would be super useful to add.

**Comment by bascht** [comment]
Soooooo – as this issue already looks like it's sentient: 

@ninabreznik could you get in contact with @sareg0 and me at `info<at>rubyberlin<dot>org` so we can figure out how the Verein can help?
@phoet Sounds doable but it would also require quite a bit of coordination for your side, I guess. :smile_cat:.

**Comment by ninabreznik** [comment]
Awesome. Will do...

@phoet What do you think about just creating APIs for us and then we build a completely standalone frontend with yo-yo NPM modules and we can then have a nice webapp and mobile app :)

**Comment by phoet** [comment]
@ninabrenzik there is an api already and there is a iOS app in the apple store using it. Feel free to do whatever you want with it. From my point of view, having a client side app introduces a level of complexity I would not want to maintain, do I'd vote against putting any funds into it.

**Comment by ninabreznik** [comment]
Hey, then maybe there is really nothing to add here. No worries, let's just enjoy using it then 👽 🤖 😺

**Comment by phoet** [comment]
In case someone is still interested in funding the project, you can become a patron for it at https://www.patreon.com/on_ruby
