### ISSUE TITLE
Try out Depfu?

### ISSUE THREAD

**Issue by halfbyte** [phoet/on_ruby#220]
@phoet Lust das mal testweise zu aktivieren? Gibt natürlich eine Lifetime-Lizenz weil wegen wichtiges Community-Projekt und so :)

Details dann gerne eher auf anderem Kanal, weil wegen privater login-link und so.

**Comment by phoet** [comment]
logo!

**Comment by phoet** [comment]
wann bekomme ich denn endlich so nen link?

**Comment by halfbyte** [comment]
You got Mail.
