### ISSUE TITLE
Ruby Version in Docker Container outdated

### ISSUE THREAD

**Issue by janz93** [phoet/on_ruby#259]
During the installation process I found that the ruby version from the Docker Container is on `2.3.0` yet the Gemfile requires `2.4.0`
`Your Ruby version is 2.3.0, but your Gemfile specified ~> 2.4.0`

**Comment by phoet** [comment]
this is partly due to #256

it would be great if you could contribute a working docker environment. i'm not using it right now and will probably not invest time into it any time soon.

**Comment by janz93** [comment]
Sure I will create a pr for it.
