### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by janz93** [phoet/on_ruby#291]
In the backend, it looks like as you can register a user.
In fact, that is not possible because you can't add their Twitter are GitHub credentials into the registration and therefore get an error message:

2 errors prohibited this page from being saved:
Nickname muss ausgefüllt werden
Image muss ausgefüllt werden

**Comment by phoet** [comment]
the behavior is intentional, the option to create a user from within the admin should be removed.

**Comment by phoet** [comment]
upsi, wrong button

**Comment by emrox** [comment]
I've tried this one. Main issue is the current user relies on the [FakeUser](https://github.com/typus/typus/blob/master/lib/support/fake_user.rb) by the Typus gem and the FakeUser does not support fine grained user rights. Refactoring this would need some time

**Comment by phoet** [comment]
@emrox thanks for looking into it. have you looked at removing the add user functionality altogether? it does not make much sense in terms of how users are handled in the app which is more kind of a cache of oauth data.

**Comment by emrox** [comment]
@phoet the add user functionality is provided by Typus and I couldn't find a clean way to prevent adding a new user without using a proper user (where rights could be set correctly, see [FakeUser#can? method](https://github.com/typus/typus/blob/master/lib/support/fake_user.rb#L7))
