### ISSUE TITLE
Remove uniqueness validation for topic name

### ISSUE THREAD

**Issue by adamniedzielski** [phoet/on_ruby#292]
I propose to remove the uniqueness validation for topic name.

1. A person may present the very same topic at multiple groups
2. Even if there was a topic "Introduction to Elixir" 2 years ago I don't see why it should prevent a different person from making a different talk with the title "Introduction to Elixir"

What do you think? If you agree I'll make the change.

**Comment by phoet** [comment]
@adamniedzielski i think it's ok to drop the constraint.

we just need to make sure that friendly-id is actually generating different slugs in that case. please be so kind to add a test-case for this scenario.
