### ISSUE TITLE
README link to Slack channel leads to app error

### ISSUE THREAD

**Issue by olleolleolle** [phoet/on_ruby#342]
Trying to find the community around this app, I clicked the link, and saw a Heroku error page.

**Comment by phoet** [comment]
to be honest, no idea if that slack group still exists...

anything i can help you with specifically?

**Comment by olleolleolle** [comment]
@phoet I'm excited about this project, and we've _just_ rebooted Malmö.rb, in Malmö, Sweden.

http://malmorb.se/ is a Middleman static website, and some of the functionality for Topics, Locations etc, would be long in the tooth to build out on one's own.

**Comment by phoet** [comment]
sure, if you like to run on onruby, there are some steps that are documented here https://github.com/phoet/on_ruby#the-guide-to-your-rug

i can run you through the onboarding if you like.

**Comment by olleolleolle** [comment]
@phoet I made a PR #343 while reading through the documentation. 

I'm interested in us using the platform. Where do I start?

Can I add the domain name in a secondary step?

**Comment by phoet** [comment]
sure, it's just a CNAME alias to your xxx.onruby.eu subdomain. you also dont give away control over the domain, it's just pointing to the app.

**Comment by olleolleolle** [comment]
Current status: _installing using Docker_

**Comment by phoet** [comment]
i hope that still works properly, currently not developing in a docker environment.

**Comment by olleolleolle** [comment]
Then we'll know soon if it does.

**Comment by PragTob** [comment]
:wave: 

As a lot of us are in the ruby berlin slack, I think we could just open an `on_ruby` channel there :)

**Comment by phoet** [comment]
@PragTob do you have a invite-app-url for that handy? we could replace the old one in the readme

**Comment by olleolleolle** [comment]
@PragTob Then, to fix this Issue, change the link and description to that. Awesome.

**Comment by PragTob** [comment]
As a matter of fact I do, will PR it :)

**Comment by phoet** [comment]
@olleolleolle please keep on opening issues and prs while you're at it!
