### ISSUE TITLE
Cannot launch www.onruby.test:5000

### ISSUE THREAD

**Issue by Adsidera** [phoet/on_ruby#457]
After having followed the README on how to install the app via Docker - `/etc/hosts`   edited as well -- `http://www.onruby.test:5000`  remains unreachable, and all other aliases addresses provided. 
`script/open`   does not work either, the address does not get resolved and turns into a `http://hamburg..xip.io:5000/`

**Comment by Adsidera** [comment]
Same for local installation, followed instructions on README but site still unaccessible. Please assist.

**Comment by phoet** [comment]
i hope this fixes the problem for you. sorry for the inconvenience
