### ISSUE TITLE
index name exceed 63 chars limits

### ISSUE THREAD

**Issue by stbnrivas** [phoet/on_ruby#502]
Hello, when I tryed run all migrations I got error because when rename histories a previous index exceed 63 limit character, this is the message.

Index name 'index_rails_admin_histories_on_item_and_table_and_month_and_year' on table 'rails_admin_histories' is too long; the limit is 63 characters /home/$user/DeveloperFork/on_ruby/db/migrate/20110311115143_rename_histories_to_rails_admin_histories.rb:3:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

I will provide a pull request for this. Thank you phoet

**Comment by phoet** [comment]
@stbnrivas are you just playing around with this for fun, or do you have something specific in mind?
