### ISSUE TITLE
Current implementation of next event calculation fails if month starts with event day

### ISSUE THREAD

**Issue by skorbut** [phoet/on_ruby#551]
Currently the hamburg on ruby page displays the 'Mittwoch, 15. Mai 2019' as next event day which is wrong since the event already occured on the 8th of may. In order to reproduce this you may use the following example in usergroup_spec.rb:
```
        context 'with the 1. of month being a wednesday' do
          let(:some_date) { Time.new(2019, 5, 9, 0, 0, 0) }
          let(:first_wednesday) { Time.new(2019, 5, 1, 0, 0, 0) }
          let(:second_wednesday) { Time.new(2019, 5, 8, 0, 0, 0) }
          let(:third_wednesday) { Time.new(2019, 5, 15, 0, 0, 0) }
          let(:last_wednesday) { Time.new(2019, 5, 29, 0, 0, 0) }

          it 'should find the right wednesday' do
            expect(rughh.parse_recurring_date(some_date)).to eql(second_wednesday)
            expect(colognerb.parse_recurring_date(some_date)).to eql(third_wednesday)
            expect(parisrb.parse_recurring_date(some_date)).to eql(last_wednesday)
          end
        end
```
A fix was provided, but was rejected in PR https://github.com/phoet/on_ruby/pull/550

**Comment by phoet** [comment]
@skorbut sorry for closing the PR that was unintentionally, most likely due to too many 🍻 will take another look at this later today. 

i had to make some changes to `parse_recurring_date` recently while upgrading to rails6. that is most likely the case for the broken date. what are those tests for then...
