### ISSUE TITLE
Unable to click attend when logged in

### ISSUE THREAD

**Issue by cameronnorman** [phoet/on_ruby#577]
I logged in with my GitHub account and was unable to 'Attend' an event. Upon clicking attend, it would ask me to login using one of the three options. Once I clicked login using GitHub it redirected me back to the event but didn't mark me attending the event. Note though that it did show me as logged in

![image](https://user-images.githubusercontent.com/6358632/60441309-03983b80-9c17-11e9-86ce-3995be29d234.png)

**Comment by phoet** [comment]
@cameronnorman sorry for the inconvenience! there are some redirects involved with the oauth flows. are you logged-in on www.rug-b.de or through berlin.onruby.de? could you try signing out and in again?

**Comment by phoet** [comment]
🤦‍♂ this part of the homepage is cached... removed it so that you can actually have a working button

**Comment by cameronnorman** [comment]
Thank you. Is there space for contributors on this project. Would love to assist

**Comment by phoet** [comment]
@cameronnorman you are welcome. i would love to get you started, just ping me if there is anything you would like to know!

i'm currently working on the redesing of the page (as you have experienced first hand) and it might be worth reading through #554 for starters.
