### ISSUE TITLE
Separate usergroup's user data

### ISSUE THREAD

**Issue by mediafinger** [phoet/on_ruby#622]
When being in the admin interface, only data from one usergroup should be visible. At the moment all data is scoped, but user data (`Authorizations`, `Users`, `Likes`, `Participations`) is global.

I didn't look at the code  yet, to check how easy this would be achievable. But a whole separation would be preferable and enable other features (like messaging all users of one usergroup).

**Comment by phoet** [comment]
I think that a good approach would be to split the "admin" part from the "community" part. Admin has all the access, community has only community access. This could be quite simple ie through different admin mounts.

**Comment by mediafinger** [comment]
Yes, that is a good idea. Maybe better a part of https://github.com/phoet/on_ruby/issues/623

**Comment by phoet** [comment]
Did not see the other issue, but yes, it's basically the same
