### ISSUE TITLE
colognerb.de is showing heroku page

### ISSUE THREAD

**Issue by sangyye** [phoet/on_ruby#659]
Hello,

https://colognerb.de is showing the heroku page instead of, I think, forward to https://www.colognerb.de page which is still showing the correct on_ruby page. I'm not sure it worked before, but I was under the impression it worked before.

DNS is looking okay
```
% dig colognerb.de

;; ANSWER SECTION:
colognerb.de.		300	IN	A	104.27.161.219
colognerb.de.		300	IN	A	104.27.160.219

;; AUTHORITY SECTION:
colognerb.de.		86027	IN	NS	graham.ns.cloudflare.com.
colognerb.de.		86027	IN	NS	janet.ns.cloudflare.com.
```

```
% dig www.colognerb.de

;; ANSWER SECTION:
www.colognerb.de.	3	IN	A	104.27.160.219
www.colognerb.de.	3	IN	A	104.27.161.219

;; AUTHORITY SECTION:
colognerb.de.		86017	IN	NS	janet.ns.cloudflare.com.
colognerb.de.		86017	IN	NS	graham.ns.cloudflare.com.
```

**Comment by phoet** [comment]
this is ok. i added the root-domain to the heroku domain settings and it works now.

cloudflare should be configured to redirect one to the other, that is so the oauth settings, that con only be configured per domain, work correctly.

**Comment by phoet** [comment]
cloudflare supports this via page rules, see this example

<img width="779" alt="Screen Shot 2020-01-16 at 11 32 31" src="https://user-images.githubusercontent.com/48745/72517586-f1e55100-3853-11ea-94d9-de79420ed93d.png">

**Comment by jhilden** [comment]
Thanks a lot @phoet 

Added the page rule:

![image](https://user-images.githubusercontent.com/69657/72522038-fc581880-385c-11ea-9907-a24d9603d266.png)

Works for me.  If somebody else can confirm.  The ticket can be closed.

**Comment by sangyye** [comment]
Thanks @jhilden and @phoet 

Works for me now.

**Comment by phoet** [comment]
@sangyye thanks for bringing this to our attention
